baseURL = 'https://mariaestmag.github.io/hugo-first/'
languageCode = 'es-es'
title = 'Descubre Almeria'
theme = "minimal"
canonifyURLs = "true"

[params]
    author = "María Estévez"
    description = "Más allá del eterno sol y la belleza inﬁnita de sus playas."
    githubUsername = "mariaestmag"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" 
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/almerienses/"
    name = "Almerienses"
    weight = 2

[[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 3

[[menu.main]]
    url = "/contacto/"
    name = "Contacto"
    weight = 4

[[menu.main]]
    url = "/gastronomia/"
    name = "Gastronomia"
    weight = 5

[[menu.main]]
    url = "/historia/"
    name = "Historia"
    weight = 6

[[menu.main]]
    url = "/search/"
    name = "Search"
    weight = 7


[[menu.icon]]
    url = "maria.est.mag@gmail.com"
    name = "fas fa-envelope"
    weight = 8

[[menu.icon]]
    url = "https://github.com/mariaestmag/"
    name = "fab fa-github"
    weight = 9

[outputs]
	home = [ "HTML", "JSON", "RSS"]